kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/pluto
    build_args:
    - VERSION=4.0.5
    tags:
    - latest
    - "4.0.5"
    - "4.0"

trigger:
  event:
  - push
  branch:
  - master
